### ISSUE TITLE
The Debug targets are not including the .pdb files

### ISSUE THREAD

**Issue by joseangelmt** [smasherprog/Libjpeg-Turbo_Nuget#3]
The nuget package is not including the the .PDB files for the Debug targets, so when you link Debug you get about 29 LNK4099 warning messages.

**Comment by smasherprog** [comment]
You're right. I am no longer going to support this package, but if you issue a PR to fix it ill republish the nuget package.

I use vcpkg now instead as that seems to be the way forward for native libraries.

**Comment by smasherprog** [comment]
I am going to close this for now. Please issue a PR if you want me to update the nuget package.
